### PR TITLE
Feature/tableview filter

### PR DESCRIPTION
**Pull request by jeremy-ingenuity**
Hi again, good day! I would like to update the TableView filter implementation. This time, using multiple filters is now supported and code for filtering is simplified.

- ~~support for multiple filters (this would update the filtering method in the handler, currently trying to have a filter class to store different filters selected by the user)~~
- ~~implement in sample app (for this repo only)~~
- ~~code cleanup (for this feature only)~~
- ~~update README~~ (I think it would be best if the author should be the one who will update the README)
- currently I am trying to implement handling of dataset pagination so that the TableView will not be crowded with too much data

NOTES:
- Since sorting and filtering implementations uses the same data source (the adapters), both features can be used without conflict, but sorting will be lost after filtering considering that the data set was sorted first. It works fine when the data set is filtered first then sorted. I will look into it, since the data set used for filtering is the original table view adapters, therefore any sorting will not be stored before filtering.

device-2018-02-03-154521

### CODE REVIEW

**Comment by evrencoskun** [comment]
Hi @jeremy-ingenuity,

> Since sorting and filtering implementations uses the same data source (the adapters), both features can be used without conflict, but sorting will be lost after filtering considering that the data set was sorted first. It works fine when the data set is filtered first then sorted. I will look into it, since the data set used for filtering is the original table view adapters, therefore any sorting will not be stored before filtering.

Okey. I will also check it out today 👍 

> (I think it would be best if the author should be the one who will update the README)

Okey. Tonight a new version will be released. Therefore, I am gonna edit the README  as well. I will make a new topic for Filtering feature on "Table of Contents". You can update the README after that time or you can send me the notes for usage. It's up to you. 

Co

> currently I am trying to implement handling of dataset pagination so that the TableView will not be crowded with too much data

Sounds good! :)

During the day, I think about working on optimization, which is related to the calculation of the width of the columns. And I also create a CONTRIBUTORS.md file  in order to honor the contributors like you :)

Thank you so much again for your collobration @jeremy-ingenuity .

**Comment by jeremy-ingenuity** [comment]
Ok noted, thanks. I'm really glad I contributed. I've tried other tableview libraries before but this one is the best implementation. Kindly review my codes carefully and tell if if something needs to be revised, or just change it in your end, especially method and variable names. Good luck!

**Comment by jeremy-ingenuity** [comment]
Btw, I tried finding a workaround for sorting -> filtering scenario and tried this:
untitled

the problem is, once the tableview is in sorted state and filtered, there is no way to set the sort state to unsorted and use the original dataset. Current implementation for filtering always uses the original adapter dataset.

**Comment by evrencoskun** [comment]
> Kindly review my codes carefully and tell if if something needs to be revised, or just change it in your end, especially method and variable names. Good luck!

Sure! Tonight, I'm going to review the code. And if necessary, I will give you some feedback. 
So, I will release the new version tomorrow night.

Thanks again also for kind words 👍

**Pull request merged**
